version: '3.7'
services:
  web:
    image: apache:satellite
    volumes:
      - ./website:/var/www/html:cached
      - ./certs:/etc/letsencrypt
      - ./certs/var/lib:/var/lib/letsencrypt
      - ./scripts:/scripts
    environment:
      WEBSITE_DOMAIN: <insert_website_domain>
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=152428800
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupaldb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: asdasdasd
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin:4.8.0
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 200MB
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
